### ISSUE TITLE
Gruntfile.js

### ISSUE THREAD

**Issue by jfenton** [geelen/a-gif-odyssey#1]
Hey Glen,

Enjoyed your x-gif talk at JSConf the other day. Wanted to show a friend the presentation in lieu of the video appearing, but seems Gruntfile.js isn't committed? (or I'm being stupid and don't know how to reconstitute).

Jay

**Comment by geelen** [comment]
I'm using gulp and I'm pretty sure I committed my gulp file. Can check when
I'm on my comp later

**Comment by jfenton** [comment]
Ah, the README threw me off. Got it! Thanks.
